apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-service-test
    tier: backend1
  name: http-service-test
  namespace: dev
spec:
  ports:
  - port: 8080
  selector:
    app: http-service-example
    gitHash: "123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    gitHash: "123"
  name: http-service-example-v2
  namespace: dev
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: http-service-example
        version: "2"
    spec:
      containers:
      - image: jpweber/http-service-test:2.2.0
        name: http-server-test
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: http-service-test
  name: http-service-test
  namespace: dev
spec:
  rules:
  - host: test.supercomputerrobot.com
    http:
      paths:
      - backend:
          serviceName: http-service-test
          servicePort: 8080
        path: /
