---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http-service-test
  labels:
    app: http-service-test 
spec:
  rules:
  - host: app1.supercomputerrobot.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: http-service-test 
          servicePort: 8080      